/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fdf9e9',
        'surface-dim': '#dedacb',
        'surface-bright': '#fdf9e9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8f4e4',
        'surface-container': '#f2eede',
        'surface-container-high': '#ece8d9',
        'surface-container-highest': '#e6e3d3',
        'on-surface': '#1c1c13',
        'on-surface-variant': '#3d4a3e',
        'inverse-surface': '#323126',
        'inverse-on-surface': '#f5f1e1',
        outline: '#6d7b6d',
        'outline-variant': '#bccabb',
        'surface-tint': '#006d36',
        primary: '#006d36',
        'on-primary': '#ffffff',
        'primary-container': '#4ade80',
        'on-primary-container': '#005e2d',
        'inverse-primary': '#4de082',
        secondary: '#0060ac',
        'on-secondary': '#ffffff',
        'secondary-container': '#64a8fe',
        'on-secondary-container': '#003c70',
        tertiary: '#a43073',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ffacd2',
        'on-tertiary-container': '#932265',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fdf9e9',
        'on-background': '#1c1c13',
        'surface-variant': '#e6e3d3',
        // legacy aliases
        'talkart-bg': '#fdf9e9',
        'talkart-surface': '#f8f4e4',
        'talkart-canvas': '#ffffff',
        'talkart-primary': '#006d36',
        'talkart-success': '#4ade80',
        'talkart-warning': '#fbbf24',
        'talkart-error': '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '48px',
        'margin-mobile': '20px',
        'stack-gap': '16px',
        gutter: '24px',
        base: '8px',
      },
      fontFamily: {
        quicksand: ['Quicksand', 'sans-serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '30px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'label-bold': ['18px', { lineHeight: '24px', fontWeight: '700' }],
      },
      boxShadow: {
        'tactile-1': '0px 4px 0px 0px rgba(0,0,0,0.05)',
        'tactile-btn': '0px 6px 0px 0px var(--tw-shadow-color)',
        'tactile-header': '0px 4px 0px 0px rgba(0,0,0,0.05)',
        ambient: '0px 20px 40px -10px rgba(0,0,0,0.1)',
        'nav-top': '0px -4px 10px rgba(0,0,0,0.05)',
      },
      animation: {
        'gentle-bounce': 'gentle-bounce 3s ease-in-out infinite',
      },
      keyframes: {
        'gentle-bounce': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
      },
    },
  },
  plugins: [],
};
